// src/lib/mock-data.ts
// Demo data so the frontend works without Strapi running

import { BlogPost, BlogCategory, Author } from './strapi';

export const MOCK_AUTHORS: Author[] = [
  {
    id: 1,
    name: 'Flarize Team',
    slug: 'flarize-team',
    role: 'Solar Energy Experts',
    bio: 'The Flarize team brings 8+ years of solar installation experience in Kerala through Golden Ray Renewable Energy.',
    credentialBadge: '500+ Installations',
    credentialColor: 'green',
  },
];

export const MOCK_CATEGORIES: BlogCategory[] = [
  { id: 1, name: 'Subsidy & Cost', slug: 'subsidy-cost', description: 'Guides on solar subsidies, pricing, and financial analysis', color: '#ea580c', icon: '💰', order: 1 },
  { id: 2, name: 'How-To Guides', slug: 'how-to', description: 'Step-by-step solar installation and process guides', color: '#2563eb', icon: '📋', order: 2 },
  { id: 3, name: 'District Guides', slug: 'district-guide', description: 'Solar information specific to Kerala districts', color: '#16a34a', icon: '📍', order: 3 },
  { id: 4, name: 'Comparisons', slug: 'comparison', description: 'Solar product and service comparisons', color: '#7c3aed', icon: '⚖️', order: 4 },
  { id: 5, name: 'News & Updates', slug: 'news-trending', description: 'Latest solar policy news and industry updates', color: '#dc2626', icon: '📰', order: 5 },
];

export const MOCK_POSTS: BlogPost[] = [
  {
    id: 1,
    documentId: 'abc123',
    title: 'Solar Panel Subsidy in Kerala 2026: Complete Guide to ₹78,000 PM Surya Ghar Scheme',
    slug: 'solar-subsidy-kerala-2026',
    subtitle: 'Step-by-step guide to claiming ₹78,000 solar subsidy in Kerala. Includes eligibility, portal walkthrough, real timelines, and common rejection reasons.',
    category: MOCK_CATEGORIES[0],
    author: MOCK_AUTHORS[0],
    publishedDate: '2026-01-15',
    updatedDate: '2026-02-09',
    readTime: 12,
    isFeatured: true,
    postType: 'subsidy-cost',
    urgencyStrip: '⚡ ~50 MW remaining out of 200 MW Kerala allocation — apply before it runs out',
    body: [
      {
        __component: 'blocks.rich-text',
        id: 1,
        content: 'The PM Surya Ghar Muft Bijli Yojana provides a **fixed subsidy up to ₹78,000** for residential rooftop solar in Kerala.\n\nBut here\'s the thing most guides won\'t tell you:\n\n**Kerala\'s allocation is running out.** Of the 200 MW allocated, roughly 150 MW has already been consumed. At the current rate, the remaining capacity could be exhausted by mid-2026.',
      },
      {
        __component: 'blocks.proof-image',
        id: 2,
        image: { url: '', width: 800, height: 450 },
        caption: 'Kerala\'s PM Surya Ghar allocation status as of Feb 2026 (Source: MNRE Dashboard)',
        alt: 'MNRE Dashboard showing Kerala solar subsidy allocation — 150 out of 200 MW consumed',
      },
      {
        __component: 'blocks.rich-text',
        id: 3,
        content: 'In this guide, I\'ll cover exactly how much you can get, how to apply, realistic timelines, and the rejection reasons nobody talks about.\n\nLet\'s dive in.\n\n## How Much Subsidy Can You Actually Get?\n\nThe subsidy under PM Surya Ghar is **fixed Central Financial Assistance (CFA)** — not percentage-based like older schemes.\n\nHere\'s the exact breakdown:',
      },
      {
        __component: 'blocks.stat-row',
        id: 4,
        stats: [
          { value: '₹30K', label: '1 kW system', color: 'brand' },
          { value: '₹60K', label: '2 kW system', color: 'brand' },
          { value: '₹78K', label: '3 kW+ (cap)', color: 'brand' },
        ],
      },
      {
        __component: 'blocks.rich-text',
        id: 5,
        content: 'Whether you install 3 kW or 10 kW — the **maximum subsidy is capped at ₹78,000**.\n\nThat\'s why 3 kW is the sweet spot for most Kerala homes. Best subsidy-to-cost ratio.',
      },
      {
        __component: 'blocks.proof-image',
        id: 6,
        image: { url: '', width: 800, height: 500 },
        caption: 'Real customer invoice for a 3kW system in Alappuzha. After subsidy: ₹1.27L out of pocket.',
        alt: 'Flarize customer invoice showing 3kW solar system cost breakdown',
      },
      {
        __component: 'blocks.rich-text',
        id: 7,
        content: 'After subsidy, your out-of-pocket for a 3 kW system drops to **₹1.1L – ₹1.4L**.\n\nThese numbers come from our actual customer invoices — not industry averages.',
      },
      {
        __component: 'blocks.callout',
        id: 8,
        type: 'insight',
        content: '**Pro tip:** If your bimonthly KSEB bill is ₹3,000–₹6,000, a 3 kW system is typically the right fit. Going bigger doesn\'t get you more subsidy — it just increases your upfront cost.',
      },
      {
        __component: 'blocks.testimonial-ref',
        id: 9,
        quote: 'We paid ₹2.05L for a 3kW system. The ₹78,000 subsidy hit our bank in 28 days. Effective cost: ₹1.27L. Bimonthly bill went from ₹4,800 to ₹380.',
        customerName: 'Jose V P',
        detail: '3kW · Vadakkal, Alappuzha · Dec 2025',
      },
      {
        __component: 'blocks.cta-calculator',
        id: 10,
        heading: 'See your actual savings in 30 seconds',
        description: 'Enter your bimonthly KSEB bill amount.',
        buttonText: 'Calculate Savings →',
        calculatorType: 'savings',
      },
      {
        __component: 'blocks.rich-text',
        id: 11,
        content: '## Eligibility: Who Can Get the Subsidy?\n\nNot everyone qualifies. Here are the hard requirements:\n\n- **Residential connection only** — commercial/industrial doesn\'t qualify\n- **Active KSEB consumer number** — your connection must be live\n- **First-time installation** — no previous government solar subsidy\n- **ALMM-listed panels only** — cheap imports don\'t qualify\n- **KSEB-empanelled vendor** — you can\'t DIY or use random contractors',
      },
      {
        __component: 'blocks.callout',
        id: 12,
        type: 'warning',
        content: '**Warning:** Some vendors claim to be "empanelled" but aren\'t. Always verify on KSEB\'s official E-Kiran portal before signing anything. We\'ve seen customers lose their subsidy eligibility because of this.',
      },
      {
        __component: 'blocks.rich-text',
        id: 13,
        content: '## National Portal vs Soura: Which Path Should You Choose?\n\nKerala offers **two paths** to the same subsidy. Most guides don\'t explain the difference clearly.\n\nHere\'s the honest comparison:',
      },
      {
        __component: 'blocks.comparison-table',
        id: 14,
        tableData: {
          headers: ['Feature', 'National Portal', 'Soura (KSEB)'],
          rows: [
            { 'Feature': 'Payment', 'National Portal': 'Pay full → subsidy reimbursed', 'Soura (KSEB)': 'Subsidy deducted upfront' },
            { 'Feature': 'Vendor choice', 'National Portal': 'You choose (any empanelled)', 'Soura (KSEB)': 'KSEB assigns from list' },
            { 'Feature': 'Processing speed', 'National Portal': 'Faster (you drive the process)', 'Soura (KSEB)': 'Slower (batch processing)' },
            { 'Feature': 'Upfront cost', 'National Portal': 'Higher (full amount)', 'Soura (KSEB)': 'Lower (subsidy pre-deducted)' },
            { 'Feature': 'Best for', 'National Portal': 'Control & speed', 'Soura (KSEB)': 'Lowest cash outlay' },
          ],
        },
      },
      {
        __component: 'blocks.rich-text',
        id: 15,
        content: 'Our recommendation: **Go National Portal** if you can afford the upfront cost. It\'s faster, and you choose your own vendor.\n\nGo Soura if budget is tight and you don\'t mind waiting longer.',
      },
      {
        __component: 'blocks.cta-proof',
        id: 16,
        stats: [
          { value: '500+', label: 'Homes Powered' },
          { value: '75%', label: 'Avg Bill Drop' },
          { value: '28 Days', label: 'Avg Subsidy Time' },
        ],
        description: 'Join 500+ Kerala families who switched with Flarize',
        primaryButton: { text: 'See Our Projects →', url: '/projects', style: 'dark' },
        secondaryButton: { text: 'Read Customer Stories', url: '/testimonials', style: 'outline' },
      },
      {
        __component: 'blocks.rich-text',
        id: 17,
        content: '## Real Timeline: How Long It Actually Takes\n\nEvery website says "4-6 weeks." Here\'s what actually happens:\n\n**Total realistic timeline: 45-60 days.**\n\n- **TFR approval:** 7-15 days (depends on your KSEB section)\n- **Vendor selection & installation:** 2-3 days (Flarize average)\n- **KSEB inspection:** 7-14 days (major bottleneck)\n- **Net meter installation:** 7-14 days\n- **Subsidy credit to bank:** 15-30 days after commissioning',
      },
      {
        __component: 'blocks.callout',
        id: 18,
        type: 'tip',
        content: '**Real talk:** The KSEB inspection is the biggest variable. Some sections process in 7 days, others take 3 weeks. Flarize has direct coordination with local KSEB offices which typically speeds this up.',
      },
      {
        __component: 'blocks.rich-text',
        id: 19,
        content: '## Common Rejection Reasons (and How to Avoid Them)\n\nAbout **12% of applications** get rejected or delayed. Here are the top reasons:\n\n### 1. Transformer capacity exceeded\n\nToo many homes on your transformer already have solar. KSEB caps solar capacity per transformer at 80%.\n\n**Fix:** Apply early. Once your transformer hits the cap, you\'re waitlisted.\n\n### 2. Consumer number mismatch\n\nKSEB records don\'t match your application details.\n\n**Fix:** Cross-check your name, address, and consumer number against your latest KSEB bill before applying.\n\n### 3. Non-ALMM panels\n\nYour vendor used panels that aren\'t on MNRE\'s Approved List.\n\n**Fix:** Demand the ALMM certificate from your vendor *before* installation begins.',
      },
      {
        __component: 'blocks.callout',
        id: 20,
        type: 'brand',
        content: '**Flarize guarantee:** We only use ALMM-listed panels from Tier-1 manufacturers. Every installation comes with panel certificates, inverter warranty cards, and complete KSEB documentation.',
      },
      {
        __component: 'blocks.cta-hard',
        id: 21,
        heading: 'Ready to stop paying high KSEB bills?',
        description: 'Free consultation. Free site assessment. We handle all paperwork.',
        primaryButton: { text: 'Book Free Consultation →', url: '/contact', style: 'brand' },
        secondaryButton: { text: 'Call: +91 XXXX XXXXXX', url: 'tel:+91XXXXXXXXXX', style: 'ghost' },
      },
      {
        __component: 'blocks.faq-section',
        id: 22,
        heading: 'Frequently Asked Questions',
        questions: [
          { question: 'Can I get the subsidy if I already have solar?', answer: 'No. PM Surya Ghar is for first-time residential installations only. If you\'ve received any previous government solar subsidy, you\'re not eligible.' },
          { question: 'How much roof space do I need for a 3kW system?', answer: 'Approximately 250-300 sq ft of shadow-free area. Rule of thumb: 100 sq ft per kW. Must be shadow-free between 9 AM and 4 PM.' },
          { question: 'Is the subsidy a discount or reimbursement?', answer: 'National Portal: reimbursement (pay full, subsidy comes to bank in 15-30 days). Soura: deducted upfront from system cost.' },
          { question: 'Do solar panels work during Kerala monsoon?', answer: 'Yes, at 30-50% of peak capacity. Kerala monsoon months produce ~60-70% of annual average. Our savings estimates account for this.' },
          { question: 'Can NRIs apply for the solar subsidy?', answer: 'Yes — if the KSEB connection is in their name and the property is residential. NRIs can authorize a family member for on-site process. Flarize offers a complete NRI package with video updates.' },
          { question: 'What happens to excess power I generate?', answer: 'Exported to KSEB grid via net metering. You get credits that offset future bills. Surplus at year-end compensated at APPC rate.' },
        ],
      },
    ],
    seo: {
      metaTitle: 'Solar Panel Subsidy in Kerala 2026: ₹78,000 PM Surya Ghar Guide',
      metaDescription: 'Complete guide to claiming ₹78,000 solar subsidy in Kerala through PM Surya Ghar Yojana. Eligibility, portal walkthrough, real timelines.',
    },
    relatedPosts: [
      { id: 2, documentId: 'def456', title: 'Solar Panel Price in Kerala 2026: Complete Cost Breakdown', slug: 'solar-panel-price-kerala-2026', publishedDate: '2026-01-20', readTime: 10, isFeatured: false, category: MOCK_CATEGORIES[0], body: [] } as any,
      { id: 3, documentId: 'ghi789', title: 'How to Install Solar Panels in Kerala: Step-by-Step', slug: 'how-to-install-solar-kerala', publishedDate: '2026-01-25', readTime: 8, isFeatured: false, category: MOCK_CATEGORIES[1], body: [] } as any,
      { id: 4, documentId: 'jkl012', title: 'Is Solar Worth It in Kerala? Real ROI Analysis', slug: 'is-solar-worth-it-kerala', publishedDate: '2026-02-01', readTime: 15, isFeatured: false, category: MOCK_CATEGORIES[0], body: [] } as any,
    ],
  },
  {
    id: 2,
    documentId: 'def456',
    title: 'Solar Panel Price in Kerala 2026: Complete Cost Breakdown',
    slug: 'solar-panel-price-kerala-2026',
    subtitle: 'Real pricing data from 500+ installations. System costs, hidden fees, and how to avoid overpaying.',
    category: MOCK_CATEGORIES[0],
    author: MOCK_AUTHORS[0],
    publishedDate: '2026-01-20',
    readTime: 10,
    isFeatured: false,
    postType: 'subsidy-cost',
    body: [
      { __component: 'blocks.rich-text', id: 1, content: '## What Does a Solar Panel System Actually Cost in Kerala?\n\nThe short answer: **₹55,000 – ₹70,000 per kW** for a quality on-grid system with installation.\n\nBut the real answer depends on your system size, panel brand, inverter type, and mounting structure.' },
    ],
    seo: { metaTitle: 'Solar Panel Price Kerala 2026 — Real Cost from 500+ Installations' },
    relatedPosts: [],
  },
  {
    id: 3,
    documentId: 'ghi789',
    title: 'How to Install Solar Panels in Kerala: Step-by-Step KSEB Process',
    slug: 'how-to-install-solar-kerala',
    subtitle: 'From KSEB application to net meter activation — every step with realistic timelines.',
    category: MOCK_CATEGORIES[1],
    author: MOCK_AUTHORS[0],
    publishedDate: '2026-01-25',
    readTime: 8,
    isFeatured: false,
    postType: 'how-to',
    body: [
      { __component: 'blocks.rich-text', id: 1, content: '## Step 1: Check Your Eligibility\n\nBefore anything else, confirm you have an **active residential KSEB connection** and your transformer has available solar capacity.' },
    ],
    seo: { metaTitle: 'How to Install Solar Panels in Kerala — KSEB Process Guide' },
    relatedPosts: [],
  },
  {
    id: 4,
    documentId: 'jkl012',
    title: 'Is Solar Worth It in Kerala? Real ROI Analysis with Numbers',
    slug: 'is-solar-worth-it-kerala',
    subtitle: 'We calculated the exact ROI from 500+ installations. Here are the real numbers.',
    category: MOCK_CATEGORIES[0],
    author: MOCK_AUTHORS[0],
    publishedDate: '2026-02-01',
    readTime: 15,
    isFeatured: true,
    postType: 'subsidy-cost',
    body: [
      { __component: 'blocks.rich-text', id: 1, content: '## The Bottom Line: Is Solar Worth It?\n\n**Yes — if your bimonthly KSEB bill is ₹2,000 or more.** At current electricity rates and subsidy levels, a 3kW system pays for itself in 3.5-4.5 years.' },
    ],
    seo: { metaTitle: 'Is Solar Worth It in Kerala? Real ROI from 500+ Installations' },
    relatedPosts: [],
  },
  {
    id: 5,
    documentId: 'mno345',
    title: 'Solar Panel Installation in Alappuzha: District Guide 2026',
    slug: 'solar-panel-alappuzha-guide',
    subtitle: 'Everything about going solar in Alappuzha — local installers, salt corrosion concerns, and district-specific data.',
    category: MOCK_CATEGORIES[2],
    author: MOCK_AUTHORS[0],
    publishedDate: '2026-02-05',
    readTime: 9,
    isFeatured: false,
    postType: 'district-guide',
    body: [
      { __component: 'blocks.rich-text', id: 1, content: '## Solar in Alappuzha: What You Need to Know\n\nAlappuzha\'s coastal location means **higher humidity and salt air exposure**. This affects panel and mounting frame longevity if you don\'t choose the right materials.' },
    ],
    seo: { metaTitle: 'Solar Panels in Alappuzha 2026 — District Guide' },
    relatedPosts: [],
  },
  {
    id: 6,
    documentId: 'pqr678',
    title: 'On-Grid vs Hybrid Solar in Kerala: Which Should You Choose?',
    slug: 'on-grid-vs-hybrid-solar-kerala',
    subtitle: 'Honest comparison with real cost data. Most people don\'t need hybrid — here\'s why.',
    category: MOCK_CATEGORIES[3],
    author: MOCK_AUTHORS[0],
    publishedDate: '2026-02-08',
    readTime: 11,
    isFeatured: false,
    postType: 'comparison',
    body: [
      { __component: 'blocks.rich-text', id: 1, content: '## The Verdict: On-Grid for Most Kerala Homes\n\n**On-grid wins for 85% of Kerala homeowners.** The math is simple: hybrid systems cost 40-60% more but only add value if you experience frequent, extended power cuts.' },
    ],
    seo: { metaTitle: 'On-Grid vs Hybrid Solar Kerala — Honest Comparison' },
    relatedPosts: [],
  },
];

// Helper to check if we should use mock data
export const USE_MOCK = !process.env.NEXT_PUBLIC_STRAPI_URL || process.env.NEXT_PUBLIC_STRAPI_URL === 'http://localhost:1337';
